/**
 * @file home_html.h 
 * @author Ben Marples
 * @brief Holds the human readable version of the html page
 */
#ifndef HOME_HTML_H
#define HOME_HTML_H

static const char *home_hmtl =
    "<head>\n"
    "<style>\n"
    "tr,th,td {\n"
    "    border:1px solid black;\n"
    "}\n"
    "</style>\n"
    "</head>\n"
    "\n"
    "<body>\n"
    "\n"
    "<script>\n"
    "function updateGPIOFromJSON(data) {\n"
    "    if (!data || !data.pins) {\n"
    "        console.error(\"Invalid GPIO JSON:\", data);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    const pins = data.pins;\n"
    "\n"
    "    Object.keys(pins).forEach(pinNum => {\n"
    "        const pinData = pins[pinNum];\n"
    "\n"
    "        const modeSelect = document.querySelector(`select[name=\"pin${pinNum}\"]`);\n"
    "        if (modeSelect) {\n"
    "            modeSelect.value = String(pinData.mode);\n"
    "        }\n"
    "\n"
    "        const ioSelect = document.querySelector(`select[name=\"pin${pinNum}-io\"]`);\n"
    "        if (ioSelect) {\n"
    "            ioSelect.value = String(pinData.io);\n"
    "        }\n"
    "    });\n"
    "}\n"
    "function updateNetworkFromJSON(data) {\n"
    "    if (!data) {\n"
    "        console.error(\"Invalid Network JSON:\", data);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    \n"
    "    const modeAP  = document.querySelector('input[name=\"mode\"][value=\"AP\"]');\n"
    "    const modeSTA = document.querySelector('input[name=\"mode\"][value=\"STA\"]');\n"
    "\n"
    "    if (data.mode === \"AP\" && modeAP)  modeAP.checked = true;\n"
    "    if (data.mode === \"STA\" && modeSTA) modeSTA.checked = true;\n"
    "\n"
    "    \n"
    "    const apSSID = document.querySelector('input[name=\"AP-SSID\"]');\n"
    "    const apPass = document.querySelector('input[name=\"AP-Password\"]');\n"
    "\n"
    "    if (apSSID) apSSID.value = data.AP_SSID || \"\";\n"
    "    if (apPass) apPass.value = data.AP_Password || \"\";\n"
    "\n"
    "    \n"
    "    const staSSID = document.querySelector('input[name=\"STA-SSID\"]');\n"
    "    const staPass = document.querySelector('input[name=\"STA-Password\"]');\n"
    "\n"
    "    if (staSSID) staSSID.value = data.STA_SSID || \"\";\n"
    "    if (staPass) staPass.value = data.STA_Password || \"\";\n"
    "}\n"
    "\n"
    "function updateOSCFromJSON(data) {\n"
    "    if (!data) {\n"
    "        console.error(\"Invalid OSC JSON:\", data);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    const remoteIP   = document.querySelector('input[name=\"OSC-Remote\"]');\n"
    "    const remotePort = document.querySelector('input[name=\"OSC-Remote-Port\"]');\n"
    "    const localIP    = document.querySelector('input[name=\"OSC-Local\"]');\n"
    "    const localPort  = document.querySelector('input[name=\"OSC-Local-Port\"]');\n"
    "\n"
    "    if (remoteIP)   remoteIP.value   = data.remote_ip   || \"\";\n"
    "    if (remotePort) remotePort.value = data.remote_port || \"\";\n"
    "    if (localIP)    localIP.value    = data.local_ip    || \"\";\n"
    "    if (localPort)  localPort.value  = data.local_port  || \"\";\n"
    "}\n"
    "\n"
    "document.addEventListener(\"DOMContentLoaded\", () => {\n"
    "    fetch(\"/gpio.json\")\n"
    "        .then(res => res.json())\n"
    "        .then(json => updateGPIOFromJSON(json))\n"
    "        .catch(err => console.error(\"Failed to load GPIO JSON:\", err));\n"
    "    \n"
    "    \n"
    "    fetch(\"/network.json\")\n"
    "        .then(res => res.json())\n"
    "        .then(json => updateNetworkFromJSON(json))\n"
    "        .catch(err => console.error(\"Failed to load Network JSON:\", err));\n"
    "\n"
    "    \n"
    "    fetch(\"/osc.json\")\n"
    "        .then(res => res.json())\n"
    "        .then(json => updateOSCFromJSON(json))\n"
    "        .catch(err => console.error(\"Failed to load OSC JSON:\", err));\n"
    "});\n"
    "</script>\n"
    "\n"
    "\n"
    "\n"
    "<section>\n"
    "    <h1>Network</h1>\n"
    "    <form method=\"get\" action=\"/network\">\n"
    "        <p>Network Type:</p>\n"
    "    <input type=\"radio\" name=\"mode\" value=\"AP\"> Self Host\n"
    "    <input type=\"radio\" name=\"mode\" value=\"STA\"> Join Network\n"
    "    <br>\n"
    "    <!-- AP -->\n"
    "    <h3> Access Point Mode (Self Host) </h3>\n"
    "    <label for=\"AP-SSID\">SSID</label>\n"
    "    <input type=\"text\" name=\"AP-SSID\">\n"
    "    <br>\n"
    "    <label for=\"AP-Password\">Password</label>\n"
    "    <input type=\"text\" name=\"AP-Password\">\n"
    "\n"
    "    <br>\n"
    "    <!-- STA -->\n"
    "    <h3> Station Mode (Join Network) </h3>\n"
    "    <label for=\"STA-SSID\">SSID</label>\n"
    "    <input type=\"text\" name=\"STA-SSID\">\n"
    "    <br>\n"
    "    <label for=\"STA-Password\">Password</label>\n"
    "    <input type=\"text\" name=\"STA-Password\">\n"
    "    <br>\n"
    "    <button type=\"submit\" style=\"column-span: 3;\">Update Network Configuration</button>        \n"
    "\n"
    "    </form>\n"
    "    \n"
    "</section>\n"
    "\n"
    "<section>\n"
    "    <h1>OSC</h1>\n"
    "    <form method=\"get\" action=\"/OSC\">\n"
    "    <!-- OSC -->\n"
    "    <label for=\"OSC-Remote\">Remote IP</label>\n"
    "    <input type=\"text\" name=\"OSC-Remote\">\n"
    "    <label for=\"OSC-Remote-Port\">Port:</label>\n"
    "    <input type=\"number\" name=\"OSC-Remote-Port\">\n"
    "    <br>\n"
    "    <label for=\"OSC-Local\">Local IP</label>\n"
    "    <input type=\"text\" name=\"OSC-Local\">\n"
    "    <label for=\"OSC-Local-Port\">Port:</label>\n"
    "    <input type=\"number\" name=\"OSC-Local-Port\">\n"
    "    <br>\n"
    "    <button type=\"submit\" style=\"column-span: 3;\">Update OSC Configuration</button>        \n"
    "\n"
    "    </form>\n"
    "    \n"
    "</section>\n"
    "\n"
    "<section>\n"
    "<h1>GPIO</h1>    \n"
    "<form method=\"post\" action=\"/GPIO\"> \n"
    "<table>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 1</td>\n"
    "<td>\n"
    "<select name=\"pin1\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "<option value=\"1\">Analog</option>\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin1-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 2</td>\n"
    "<td>\n"
    "<select name=\"pin2\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "<option value=\"1\">Analog</option>\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin2-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 3</td>\n"
    "<td>\n"
    "<select name=\"pin3\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "<option value=\"1\">Analog</option>\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin3-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 4</td>\n"
    "<td>\n"
    "<select name=\"pin4\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "<option value=\"1\">Analog</option>\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin4-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 5</td>\n"
    "<td>\n"
    "<select name=\"pin5\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "<option value=\"1\">Analog</option>\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin5-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 6</td>\n"
    "<td>\n"
    "<select name=\"pin6\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "<option value=\"1\">Analog</option>\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin6-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 7</td>\n"
    "<td>\n"
    "<select name=\"pin7\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin7-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 8</td>\n"
    "<td>\n"
    "<select name=\"pin8\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin8-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 9</td>\n"
    "<td>\n"
    "<select name=\"pin9\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin9-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 10</td>\n"
    "<td>\n"
    "<select name=\"pin10\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin10-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 11</td>\n"
    "<td>\n"
    "<select name=\"pin11\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin11-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 12</td>\n"
    "<td>\n"
    "<select name=\"pin12\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin12-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 13</td>\n"
    "<td>\n"
    "<select name=\"pin13\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin13-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 14</td>\n"
    "<td>\n"
    "<select name=\"pin14\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin14-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 15</td>\n"
    "<td>\n"
    "<select name=\"pin15\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin15-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 16</td>\n"
    "<td>\n"
    "<select name=\"pin16\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin16-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 17</td>\n"
    "<td>\n"
    "<select name=\"pin17\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin17-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 18</td>\n"
    "<td>\n"
    "<select name=\"pin18\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin18-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 19</td>\n"
    "<td>\n"
    "<select name=\"pin19\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin19-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 20</td>\n"
    "<td>\n"
    "<select name=\"pin20\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin20-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 21</td>\n"
    "<td>\n"
    "<select name=\"pin21\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin21-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 22</td>\n"
    "<td>\n"
    "<select name=\"pin22\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin22-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 23</td>\n"
    "<td>\n"
    "<select name=\"pin23\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin23-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 24</td>\n"
    "<td>\n"
    "<select name=\"pin24\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin24-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 25</td>\n"
    "<td>\n"
    "<select name=\"pin25\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin25-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 26</td>\n"
    "<td>\n"
    "<select name=\"pin26\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin26-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 27</td>\n"
    "<td>\n"
    "<select name=\"pin27\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin27-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "\n"
    "<tr>\n"
    "<td>Pin - 28</td>\n"
    "<td>\n"
    "<select name=\"pin28\"> \n"
    "<option value=\"0\">OFF</option>\n"
    "\n"
    "<option value=\"2\">Digital</option>\n"
    "</select>\n"
    "</td>\n"
    "<td>\n"
    "    <select name=\"pin28-io\">\n"
    "        <option value=\"0\">Output</option>\n"
    "        <option value=\"1\">Input</option>\n"
    "    </select>\n"
    "</td>\n"
    "</tr>\n"
    "</table>\n"
    "<button type=\"submit\">Save </button>\n"
    "</form>\n"
    "</body>\n"
    "\n";

#endif